"""Product and Review model

Revision ID: b8abbbd7bc47
Revises: 
Create Date: 2025-02-03 03:19:22.176406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8abbbd7bc47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), nullable=True))
        batch_op.drop_column('ratings')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ratings', sa.NUMERIC(precision=3, scale=2), nullable=True))
        batch_op.drop_column('avg_rating')

    # ### end Alembic commands ###
